language: python
python:
  - "3.8"
services:
  - postgresql
install:
  - "pip install -r requirements.txt"
before_script:
  - psql -c "CREATE DATABASE public_chat;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres
script:
  - python3 manage.py test
