language: python
python:
  - "3.8"

branches:
  only:
    - master
services:
  - postgresql
install:
  - "pip install -r requirements.txt"
before_script:
  - psql -c "CREATE DATABASE public_chat;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER USER admin CREATEDB;" -U postgres
  - psql -c "ALTER ROLE admin superuser;" -U postgres
script:
  - python3 manage.py test

deploy:
  provider: heroku
  app: fathomless-spire-77077
  api_key: "eaeb3901-5995-4e2e-80bf-4201fbb52a08"
  skip_cleanup: true